/* USER CODE BEGIN 0 */
#include "motor.h"


void motor1_forward(void)
{
	// MOTOR1 前进
	HAL_GPIO_WritePin(MOTOR1_FORWARD_GPIO_Port, MOTOR1_FORWARD_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR1_BACKWARD_GPIO_Port, MOTOR1_BACKWARD_Pin, GPIO_PIN_RESET);
}

void motor1_backward(void)
{
	// MOTOR1 后退
	HAL_GPIO_WritePin(MOTOR1_FORWARD_GPIO_Port, MOTOR1_FORWARD_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR1_BACKWARD_GPIO_Port, MOTOR1_BACKWARD_Pin, GPIO_PIN_SET);
}

void motor1_stop(void)
{
	// MOTOR1 停止
	HAL_GPIO_WritePin(MOTOR1_FORWARD_GPIO_Port, MOTOR1_FORWARD_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR1_BACKWARD_GPIO_Port, MOTOR1_BACKWARD_Pin, GPIO_PIN_RESET);
}

void motor2_forward(void)
{
	// MOTOR2 前进
	HAL_GPIO_WritePin(MOTOR2_FORWARD_GPIO_Port, MOTOR2_FORWARD_Pin, GPIO_PIN_SET);
	HAL_GPIO_WritePin(MOTOR2_BACKWARD_GPIO_Port, MOTOR2_BACKWARD_Pin, GPIO_PIN_RESET);
}

void motor2_backward(void)
{
	// MOTOR2 后退
	HAL_GPIO_WritePin(MOTOR2_FORWARD_GPIO_Port, MOTOR2_FORWARD_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR2_BACKWARD_GPIO_Port, MOTOR2_BACKWARD_Pin, GPIO_PIN_SET);
}

void motor2_stop(void)
{
	// MOTOR2 停止
	HAL_GPIO_WritePin(MOTOR2_FORWARD_GPIO_Port, MOTOR2_FORWARD_Pin, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(MOTOR2_BACKWARD_GPIO_Port, MOTOR2_BACKWARD_Pin, GPIO_PIN_RESET);
}

/* USER CODE END 0 */
